# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tifuret <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/21 18:39:09 by tifuret           #+#    #+#              #
#    Updated: 2017/08/21 18:44:22 by tifuret          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SOURCES = do_op.c \
		  ft_atoi.c \
		  ft_op.c \
		  ft_putchar.c \
		  ft_putnbr.c \
		  ft_putstr.c

all : $(NAME)

$(NAME):
		gcc -o  $(NAME) $(SOURCES)

clean :
		rm -f do-op

re: clean all
